- name: variables from PLAY level
  hosts: localhost
  vars_files:
  - variables.yaml
  asks:
  - name: check variables
    ansible.builtin.debug:
      msg: "Hi, i am learning {{Course}},Trainer is {{Trainer}},Duration is {{Duration}}"